<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Tratando erros</title>
    <script>

        var video = Array()

        video[1] = Array()
        video[1]['nome'] = 'Fullmetall Alchemist'
        video[1]['categoria'] = 'Anime'

        function getVideo(video) {
            
            try {

                console.log(video[0]['nome'])

            }
            catch(erro) {

                tratarErro(erro)
                //console.log('Agora sim podemos tratar esse erro')

                //throw new Error('Houve um erro mas não se preocupe, estamos trabalhando nisso agora!!!')

            }
            finally {

                console.log('Sempre passa por aqui: (try | catch)')

            }

            console.log('A aplicação não morreu')
        }

        function tratarErro(e) {

            // Lógica para registrar esse erro no servidor
            console.log('Erro enviado ao suporte: \n' + e)

        }

        getVideo(video)

    </script>
</head>
<body>
    
    <!--
        try - tente executar
        catch - pegar o erro gerado e trata esse erro
        finally - continua a execução do pograma
        throw - lança excessões dentro das aplicações
    -->

</body>
</html>